### ISSUE TITLE
Request for Multidimensional IRT

### ISSUE THREAD

**Issue by Djokovic0311** [nd-ball/py-irt#26]
Hey @jplalor @EntilZha! 

We are working on multidimensional IRT. Could you please add commits for related to multidimensional IRT if convenient? It will be extremely helpful for our next-step heuristics ideas! Thanks in advance.

**Comment by EntilZha** [comment]
Hey, thanks for the interest! The model is actually already in the repo here https://github.com/nd-ball/py-irt/blob/master/py_irt/models/multidim_2pl.py, but it might not be quite as well integrated (its tricky since the 1d models have 1d parameters and multidim has multidim, so the shapes don't match). You might also look at the paper repository where that model is from here https://github.com/facebookresearch/irt-leaderboard

**Comment by jplalor** [comment]
Let us know if you have any questions!

**Comment by EntilZha** [comment]
@Djokovic0311 in general, loc refers to the center of the distribution which is the value you generally want and scale refers to how wide it is/variance/etc.
