### ISSUE TITLE
About MIRT value 

### ISSUE THREAD

**Issue by Djokovic0311** [nd-ball/py-irt#27]
Hi @EntilZha @jplalor 

I have a question about MIRT return value.

I check the py-irt codes and now find what we consider as ‘disc’, ‘diff’, ‘fea’ are exactly the same in mirt and sirt parts. The two models both save the ‘loc_xxxx’. The only difference is that in mirt model, you set a two dimension array(num_subjects and dims) as these parameters, while in sirt, only a single digit is used(num_subjects). 

So what does the 'dims' mean and how can I get the real MIRT value?

Thanks a lot in advance! Look forward to your reply!

**Comment by EntilZha** [comment]
Hi, so in MIRT each feature type (discrimination/difficulty/feasibility) is multidimensional. That is, in addition to difficulty having num_subjects dimensions, each subject dimension has `dims` dimensions. The MIRT value in this case for difficulty/discrimination/etc is multidimensional vector. You should be able to grab it the same way as for single dim IRT, the only difference is that it will have one more dimensions.

**Comment by Djokovic0311** [comment]
Hi, so what I should take as difficulty/discrimination/etc in MIRT the same way as for single dim IRT? Does it make sense to use the first dimension(num_subjects) as well?

**Comment by EntilZha** [comment]
I might be missing what you're asking, but the way I interpret the MIRT model is that it is proposing that difficulty can vary along more than one direction. For example, a question might be comprised of difficulty in math/science/history for a 3 dimension model (we're just supposing the parameters line up this way, nothing says that they actually will). Each question will have these three parameters. It wouldn't make sense to take only one dimension and call that the only difficulty, since the model has other difficulty parameters for that question. That is to say, the point of the MIRT model is that there is more than one difficulty parameter per question (or skill parameter per subject).

The main question I'm interested in, research-wise, is how do we figure out what each of these dimensions represent and/or how can we craft a model such that those dimensions map onto something interpretable.

**Comment by Djokovic0311** [comment]
Great explanations! Thanks a lot. I think I understand what you mean here.
