### ISSUE TITLE
Setting difficulties manually

### ISSUE THREAD

**Issue by luanpo1234** [nd-ball/py-irt#66]
I would like to train a model using difficulties that were manually preset. Is that possible?

**Comment by EntilZha** [comment]
Are they preset and fixed, or just initial values are given? Working from this notebook https://eacl2024irt.github.io/notebooks/2_IntroToIRT_jupyter.html, a rough sketch of a solution in those cases would be:
- Preset: You'll want to initialize the model, but not call train right away. So you'll have a `IrtModelTrainer` instance. At that point, what you'll want to do is modify the pyro parameters setup by the guide (so things instantiated with `pyro.param`). Off hand I don't know how to modify existing parameters, but you could modify the model to take initial values and modify the `pyro.param` calls to use those initial values.
- Fixed: I'm not 100%, but since its torch code, I'd look into making the specific hardcoded difficulties non-trainable via torch.

Hope that helps, lmk if need more suggestions!

**Comment by luanpo1234** [comment]
Thank you very much. After I have a jsonlines file with the parameters, can I use it to predict the scores of other subjects? I couldn't find a `predict` function.

**Comment by jplalor** [comment]
Yes, you can use the evaluate command line argument in that case. The code also shows how you could apply this within Python (https://github.com/nd-ball/py-irt/blob/master/py_irt/cli.py#L248).

**Comment by luanpo1234** [comment]
Thank you.
